/* eslint-disable */
// Generated by `wrangler types`. Re-run `npm run types` after changing wrangler.jsonc bindings.
declare namespace Cloudflare {
  interface Env {
    AudioRelay: DurableObjectNamespace<import("./src/worker").AudioRelay>;
  }
}
interface Env extends Cloudflare.Env {}
