/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 4249130200311f3cb8cda0ecd3517e55)
interface __BaseEnv_Env {
	AudioReceiver: DurableObjectNamespace<import("./src/worker").AudioReceiver>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "AudioReceiver";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
