/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 2c66081cc7566538d95a676647caafae)
interface __BaseEnv_Env {
	AudioRelay: DurableObjectNamespace<import("./src/worker").AudioRelay>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "AudioRelay";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
